baseURL = "https://shufang.org/"
languageCode = "en-us"
title = "一个人的书房"
theme = "ananke"
uglyurls = true

[menu]
[[menu.main]]
  identifier = 'about'
  name = '关于'
  url = '/about/'
  weight = -110
[[menu.main]]
  identifier = '2.0'
  name = '2.0'
  url = '/2.0/'
  weight = -100
