name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          
      - uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg
        
      - name: Run shell
        run: |
          file="./scripts/duration-length.txt"
          if [ ! -f "$file" ]
           then
               for i in $(cat $file); do
                   mp3=$(cat "$i" | grep "^mp3 =" | awk -F= '{print $2}')
                   duration=$(ffprobe -i "$mp3" -show_entries format=duration -v quiet -of csv="p=0" -sexagesimal)
                   length=$(ffprobe -i "$mp3" -show_entries format=size -v quiet -of csv="p=0")
                   sed -i 's/^duration = .*/duration = \"($duration)\"/g' "$i"
                   sed -i 's/^length = .*/length = ($length)/g' "$i"
                   cat "$i"
               done
          fi

      # - run: ffprobe -i "https://ting.shufang.org/shitsurakuen/lost-paradise_01-v2.mp3" -show_entries format=duration -v quiet -of csv="p=0" -sexagesimal
      # - run: ffprobe -i "https://ting.shufang.org/shitsurakuen/lost-paradise_01-v2.mp3" -show_entries format=size -v quiet -of csv="p=0"

      - name: Clone ox-hugo
        run: git clone https://github.com/jsntn/ox-hugo.git ox-hugo

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.87.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: shufang.org

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: whoami; cd ${{ secrets.WEBSITE_ABS_PATH }}; git pull
